version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: passkey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - passkey-network
  server:
    image: pazcalb/passkey-server:latest
    ports:
      - "3000:3000"
    networks:
      - passkey-network
    depends_on:
      - db
networks:
  passkey-network: