version: "3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: passkey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - passkey
  server:
    image: pazcalb/passkey-server:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RP_ID: ${RP_ID}
      ORIGIN: ${ORIGIN}
    networks:
      - passkey
networks:
  passkey: